### ISSUE TITLE
Permission for blocks does not have any effect

### ISSUE THREAD

**Issue by Portugao** [Portugao/MUPolls#1]
If we block complete module, the permissions for blocks does not have an effect, equal on which position the permission is.

**Comment by Guite** [comment]
The first permissions matching a context (component + instance) is used. As a general rule for a whole module is very generic a more specific rule needs to be before/above it.

**Comment by Portugao** [comment]
It's possible to set this kind of permission:
```
('MUPolls:ItemBlock:', "$blockinfo[title]::", ACCESS_OVERVIEW)
```
I like to set permissions to blocks and not to the frontend of the module....

**Comment by Portugao** [comment]
So how to give users access to the blocks of a module without give'em access to the complete frontend?

**Comment by Guite** [comment]
Untested:
```
MUPolls:ItemBlock: | MyTitle:: |  ACCESS_OVERVIEW

MUPolls:: | .* |  ACCESS_NONE
```

**Comment by Portugao** [comment]
I set it like you said.
Because it does not work i opened this issue. Maybe it is a core issue....

**Comment by Guite** [comment]
Which core version do you use?

**Comment by Portugao** [comment]
1.3.10

**Comment by Guite** [comment]
Is the whole block hidden or is the block visible but without any content?

**Comment by Portugao** [comment]
The complete block is hidden.

**Comment by Guite** [comment]
Contacted you in Slack

**Comment by Portugao** [comment]
No core and no MUPolls issue. Reason is embedding into Clip.
